apiVersion: v1
kind: Namespace
metadata:
  name: aries
---
apiVersion: v1
kind: Secret
metadata:
  name: aries-secrets
  namespace: aries
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@aries-postgres:5432/{{ .Values.postgres.database }}?schema=public"
  NEXTAUTH_SECRET: {{ .Values.auth.secret | quote }}
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
